In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
#Bài 1
b1=tf.zeros([2,3])
print("B1:",b1.shape)

B1: (2, 3)


In [ ]:
#Bài 2
X = [[1, 2, 3], [4, 5, 6]]
b2 = tf.zeros_like(X)
print("B2:", b2.numpy())

B2: [[0 0 0]
 [0 0 0]]


In [ ]:
#Bài 3
b3 = tf.fill([3, 2], 5)

In [ ]:
#Bài 4
b4 = tf.linspace(6.0,10.0, 50)
print("B4:", b4.numpy())

B4: [ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ]


In [ ]:
#Bài 5
b5 = tf.range(10,102,delta=2)
print("B5:", b5.numpy())

B5: [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


In [ ]:
#Bài 6
b6 = tf.random.normal([3,2],mean = 0,stddev=2)
print("B6:", b6.numpy())

B6: [[-0.49963787 -0.01625576]
 [-2.0718186   0.8178948 ]
 [-0.7045564  -1.1519448 ]]


In [ ]:
#Bài 7
b7 = tf.random.uniform([3, 2], minval=0, maxval=2)
print("B7:", b7.numpy())

B7: [[1.5803938  1.1256113 ]
 [1.2491901  0.39087057]
 [1.0506482  0.6404779 ]]


In [ ]:
#Bài 8
X8 = tf.constant([[1, 2], [3, 4], [5, 6]])
b8 = tf.random.shuffle(X8)
print("B8:", b8.numpy())

B8: [[5 6]
 [3 4]
 [1 2]]


In [ ]:
#Bài 9
X9 = tf.random.uniform([10, 10, 3])
b9 = tf.image.random_crop(X9, size=[5, 5, 3])
print("B9:",b9.numpy())

B9: [[[0.31588924 0.54951286 0.5214796 ]
  [0.8526145  0.3603208  0.28497028]
  [0.19679785 0.6006596  0.62022316]
  [0.09168923 0.07040274 0.3247689 ]
  [0.7442328  0.06068909 0.01649058]]

 [[0.5277287  0.8069118  0.3202579 ]
  [0.01283383 0.19554472 0.21286178]
  [0.6863924  0.72782445 0.70967245]
  [0.04557359 0.9816532  0.95486426]
  [0.6411251  0.90829086 0.00710928]]

 [[0.30528915 0.03190041 0.9616295 ]
  [0.4447286  0.7120527  0.68431664]
  [0.02410197 0.18031919 0.39900863]
  [0.4131714  0.63482213 0.65290964]
  [0.45682704 0.20883465 0.429541  ]]

 [[0.54889655 0.3052143  0.9750426 ]
  [0.12540829 0.21093202 0.9471948 ]
  [0.8225945  0.88250005 0.31667817]
  [0.5414231  0.69147277 0.51573455]
  [0.5953264  0.13593459 0.6114881 ]]

 [[0.99020624 0.18417013 0.7664459 ]
  [0.3277967  0.5405258  0.7643032 ]
  [0.5332053  0.99709976 0.20167279]
  [0.6062459  0.30554307 0.7123141 ]
  [0.09366035 0.06549895 0.03828549]]]


In [ ]:
#Bài 10
x10 = tf.random.uniform([5])
y10 = tf.random.uniform([5])
b10 = tf.where(x10 < y10, x10 + y10, x10 - y10)
print("B10:",x10.numpy(),y10.numpy(),b10.numpy())

B10: [0.44871652 0.4052285  0.20682716 0.12150991 0.85023737] [0.16967547 0.7271706  0.5861076  0.3685943  0.36008036] [0.27904105 1.1323991  0.7929348  0.4901042  0.490157  ]


In [ ]:
#Bài 11
x11 = tf.random.uniform([3, 2], 5, 10)
y11 = tf.random.uniform([2, 3], 15, 20)
b11 = x11 + tf.transpose(y11)
print("B11:",b11.numpy())

B11: [[23.830845 29.256632]
 [26.862213 26.065205]
 [24.177334 25.460466]]


In [ ]:
#Bài 12
@tf.function
def math_graph_ops(x, y):
    return x + y, x - y, x * y, x / y

x12 = tf.random.normal([3, 2, 2])
y12 = tf.random.normal([3, 2, 2])
add_r, sub_r, mul_r, div_r = math_graph_ops(x12, y12)
print(f"B12: Đã chuyển vào trong graph: {add_r.numpy()}")

B12: Đã chuyển vào trong graph: [[[ 1.4613861   0.4371016 ]
  [ 2.2157946  -0.8611965 ]]

 [[-0.5187356   0.38537723]
  [ 0.47350287 -0.8239691 ]]

 [[-0.4647084   1.9198196 ]
  [-0.1874601   0.0529319 ]]]


In [ ]:
#Bài 13&14
class BasicMathModel(tf.Module):
    @tf.function
    def compute(self, x, y):
        return x + y, x - y, x * y

model = BasicMathModel()
print("B13&14:")
x = float(input("Nhập số thứ nhất (x): "))
y = float(input("Nhập số thứ hai (y): "))

tong, hieu, tich = model.compute(tf.constant(x), tf.constant(y))

print(f"Tổng: {tong.numpy()}")
print(f"Hiệu: {hieu.numpy()}")
print(f"Tích: {tich.numpy()}")

B13&14:
Nhập số thứ nhất (x): 1
Nhập số thứ hai (y): 2
Tổng: 3.0
Hiệu: -1.0
Tích: 2.0


In [ ]:
#Bài 15
class PerimeterModel(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return (a + b) * 2.0

model = PerimeterModel()
print("B15:")
a = float(input("Nhập chiều dài (a): "))
b = float(input("Nhập chiều rộng (b): "))

p = model(tf.constant(a), tf.constant(b))
print(f"Chu vi hình chữ nhật là: {p.numpy()}")

B15:
Nhập chiều dài (a): 2
Nhập chiều rộng (b): 3
Chu vi hình chữ nhật là: 10.0


In [ ]:
#Bài 16
class BoxAreaModel(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xq = (a + b) * c * 2.0
        s_tp = (a * b) * 2.0 + s_xq
        return s_tp

model = BoxAreaModel()
print("B16:")
a = float(input("Nhập chiều dài đáy (a): "))
b = float(input("Nhập chiều rộng đáy (b): "))
c = float(input("Nhập chiều cao (c): "))

s = model(tf.constant(a), tf.constant(b), tf.constant(c))
print(f"Diện tích toàn phần hình hộp là: {s.numpy()}")

In [ ]:
#Bài 17&18
class TrapezoidProof(tf.Module):
    @tf.function
    def is_equal(self, side_a, side_b):
        return tf.equal(side_a, side_b)

model = TrapezoidProof()
print("B17&18:")
val_1 = float(input("Nhập độ dài cạnh thứ nhất: "))
val_2 = float(input("Nhập độ dài cạnh thứ hai: "))

check = model.is_equal(tf.constant(val_1), tf.constant(val_2))

if check.numpy():
    print("Hai cạnh bằng nhau, thỏa mãn điều kiện chứng minh.")
else:
    print("Hai cạnh không bằng nhau.")

B17&18:
Nhập độ dài cạnh thứ nhất: 12
Nhập độ dài cạnh thứ hai: 12
Hai cạnh bằng nhau, thỏa mãn điều kiện chứng minh.


In [ ]:
#Bài 19
class TriangleMidlineProof(tf.Module):
    @tf.function
    def check_n_midpoint(self, am, mb, parallel_status):
        # parallel_status là True nếu MN // BC
        is_m_midpoint = tf.equal(am, mb)
        return tf.logical_and(is_m_midpoint, parallel_status)

model = TriangleMidlineProof()
print("B19: Chứng minh NA = NC ---")
am = float(input("Nhập độ dài đoạn AM: "))
mb = float(input("Nhập độ dài đoạn MB: "))
parallel_input = input("Đoạn MN có song song với BC không? (c/k): ")

is_parallel = tf.constant(True if parallel_input.lower() == 'c' else False)
result = model.check_n_midpoint(tf.constant(am), tf.constant(mb), is_parallel)

if result.numpy():
    print("NA = NC (N là trung điểm của AC).")
else:
    print("Không đủ điều kiện chứng minh NA = NC.")

B19: Chứng minh NA = NC ---
Nhập độ dài đoạn AM: 12
Nhập độ dài đoạn MB: 4
Đoạn MN có song song với BC không? (c/k): c
Không đủ điều kiện chứng minh NA = NC.
